#!/bin/sh

#cleanup
rm -rf ob_dir
rm -f sigdelay.vcd

#run Vreilator to translate Verolog into C++, including testbench
verilator -Wall --cc --trace sigdelay.sv --exe sigdelay_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsigdelay.mk Vsigdelay

#run executable simulation fule
obj_dir/Vsigdelay