#!/bin/sh

#cleanup
rm -rf ob_dir
rm -f sinegen.vcd

#run Vreilator to translate Verolog into C++, including testbench
verilator -Wall --cc --trace sinegen.sv --exe sinegen_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen 

#run executable simulation fule
obj_dir/Vsinegen